// Cross-method bridge: export minimal templates and parse external outputs.
// Goal: quick interoperability with PySCF/QED-TDDFT/CavMD workflows.
(function (App) {
  "use strict";
  var deps = null;
  var S = { target: "pyscf", bound: false };
  var $ = function (id) { return document.getElementById(id); };

  function atomsFromResult(result) {
    if (!result || !result.atoms || !result.atoms.length) return [];
    var BOHR = 1 / App.engine.ANGSTROM_TO_BOHR;
    return result.atoms.map(function (a) {
      return { sym: App.SYMBOLS[a.Z] || "X", xyz: [a.xyz[0] * BOHR, a.xyz[1] * BOHR, a.xyz[2] * BOHR] };
    });
  }

  function atomsFromPreset(preset) {
    if (!preset || !preset.xyz || !App.engine || !App.engine.parseXYZ) return [];
    try {
      var atoms = App.engine.parseXYZ(preset.xyz);
      var BOHR = 1 / App.engine.ANGSTROM_TO_BOHR;
      return atoms.map(function (a) { return { sym: App.SYMBOLS[a.Z] || "X", xyz: [a.xyz[0] * BOHR, a.xyz[1] * BOHR, a.xyz[2] * BOHR] }; });
    } catch (e) { return []; }
  }

  function currentData() {
    var result = deps && deps.getResult ? deps.getResult() : null;
    var preset = deps && deps.getPreset ? deps.getPreset() : null;
    var prov = deps && deps.getProvenance ? deps.getProvenance() : null;
    var atoms = atomsFromResult(result);
    if (!atoms.length) atoms = atomsFromPreset(preset);
    if (!atoms.length) atoms = [{ sym: "H", xyz: [0, 0, 0] }, { sym: "H", xyz: [0, 0, 0.7414] }];
    var charge = prov && prov.charge != null ? prov.charge : (preset && preset.charge != null ? preset.charge : 0);
    var mult = prov && prov.multiplicity != null ? prov.multiplicity : (result && result.mult != null ? result.mult : (preset && preset.mult) || 1);
    var basis = (result && result.basisName) || (prov && prov.basis) || "STO-3G";
    var method = (prov && prov.method) || (result && result.scf && result.scf.uhf ? "UHF" : "RHF");
    var name = preset ? (preset.formula || preset.id || "molecule") : "custom molecule";
    return { atoms: atoms, basis: basis, charge: charge, multiplicity: mult, method: method, name: name };
  }

  function atomLines(atoms) {
    return atoms.map(function (a) { return a.sym + " " + a.xyz.map(function (v) { return v.toFixed(6); }).join(" "); }).join("\n");
  }

  function makeTemplate(target, data) {
    data = data || {};
    var atoms = data.atoms || [];
    var basis = (data.basis || "STO-3G").toLowerCase();
    var charge = data.charge || 0;
    var mult = data.multiplicity || 1;
    var spin = Math.max(0, mult - 1);
    var method = (data.method || (mult > 1 ? "UHF" : "RHF")).toUpperCase();
    var xyz = atomLines(atoms.length ? atoms : [{ sym: "H", xyz: [0, 0, 0] }, { sym: "H", xyz: [0, 0, 0.7414] }]);
    if (target === "qedtddft") {
      return [
        "# Generated by quantum-field-molecules Cross-method Bridge.",
        "# Minimal scaffold for a PySCF + QED-TDDFT-like workflow (adapt imports to your setup).",
        "from pyscf import gto, scf",
        "",
        "mol = gto.M(atom='''",
        xyz,
        "''', basis='" + basis + "', charge=" + charge + ", spin=" + spin + ")",
        "mf = scf." + (method === "UHF" ? "UHF" : "RHF") + "(mol).run()",
        "",
        "wc_ev = 8.0",
        "g_ev = 0.2",
        "polarization = (0.0, 0.0, 1.0)",
        "# qed = QEDTDDFT(mf, wc_ev=wc_ev, g_ev=g_ev, pol=polarization)",
        "# print(qed.kernel())",
        "print('SCF_ENERGY_HA =', mf.e_tot)"
      ].join("\n");
    }
    if (target === "cavmd") {
      return JSON.stringify({
        schema: "cavmd-input-v1",
        title: data.name || "molecule",
        units: { xyz: "angstrom", energy: "eV" },
        molecule: { charge: charge, multiplicity: mult, atoms: (atoms.length ? atoms : []).map(function (a) { return { symbol: a.sym, xyz: a.xyz.map(function (v) { return +v.toFixed(6); }) }; }) },
        cavity: { wc_ev: 8.0, g_ev: 0.2, polarization: [0, 0, 1] },
        notes: "Template generated from in-browser model; adapt force-field and integrator settings."
      }, null, 2);
    }
    return [
      "# Generated by quantum-field-molecules Cross-method Bridge.",
      "from pyscf import gto, scf",
      "",
      "mol = gto.M(atom='''",
      xyz,
      "''', basis='" + basis + "', charge=" + charge + ", spin=" + spin + ")",
      "mf = scf." + (method === "UHF" ? "UHF" : "RHF") + "(mol)",
      "E = mf.kernel()",
      "print('SCF_ENERGY_HA =', E)"
    ].join("\n");
  }

  function firstNum(obj, keys) {
    for (var i = 0; i < keys.length; i++) {
      var v = obj[keys[i]];
      if (typeof v === "number" && isFinite(v)) return v;
    }
    return null;
  }

  function toHa(v, unit) {
    if (!(typeof v === "number" && isFinite(v))) return null;
    var u = (unit || "").toLowerCase();
    if (u.indexOf("mev") >= 0) return v / 27211.386;
    if (u.indexOf("ev") >= 0) return v / 27.211386;
    return v;
  }

  function toEv(v, unit) {
    if (!(typeof v === "number" && isFinite(v))) return null;
    var u = (unit || "").toLowerCase();
    if (u.indexOf("mev") >= 0) return v / 1000;
    if (u.indexOf("cm") >= 0) return v / 8065.54429;
    if (/ha|eh|hartree|a\.u/.test(u)) return v * 27.211386;
    return v;
  }

  function firstMatchNum(s, specs, conv) {
    for (var i = 0; i < specs.length; i++) {
      var spec = specs[i];
      var re = spec.re || spec;
      var m = s.match(re);
      if (!m) continue;
      var num = parseFloat(m[spec.num || 1]);
      if (!isFinite(num)) continue;
      var unitA = m[spec.unitA || 2] || "";
      var unitB = m[spec.unitB || 3] || "";
      return conv(num, unitA, unitB, m);
    }
    return null;
  }

  function parseResult(text) {
    if (!text || !String(text).trim()) return { ok: false, source: "none" };
    var s = String(text).trim(), energy = null, gap = null, split = null, conv = null;
    try {
      var j = JSON.parse(s);
      energy = firstNum(j, ["energy", "E", "total_energy", "scf_energy", "etot"]);
      if (energy == null && j.scf) energy = firstNum(j.scf, ["E", "energy", "total"]);
      if (energy == null && j.results) energy = firstNum(j.results, ["energy", "total_energy"]);
      gap = firstNum(j, ["gap", "homo_lumo_gap", "gap_ev"]);
      if (gap == null && j.scf) gap = firstNum(j.scf, ["gap", "homo_lumo_gap", "gap_ev"]);
      split = firstNum(j, ["split", "rabi_split", "splitting_ev"]);
      if (split == null && j.cavity) split = firstNum(j.cavity, ["split", "rabi_split", "splitting_ev"]);
      if (typeof j.converged === "boolean") conv = j.converged;
      else if (j.scf && typeof j.scf.converged === "boolean") conv = j.scf.converged;
      return { ok: true, source: "json", energyHa: energy, gapEv: gap, splitEv: split, converged: conv };
    } catch (e) { /* text mode */ }
    energy = firstMatchNum(s, [
      /SCF[_\s-]*ENERGY[_\s-]*HA\s*[:=]\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i,
      /converged\s+SCF\s+energy\s*=\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?/i,
      /total\s+energy\s+in\s+the\s+final\s+basis\s+set\s*=\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?/i,
      /FINAL\s+SINGLE\s+POINT\s+ENERGY\s+(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?/i,
      /Total\s+Energy\s*[:=]\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?/i,
      /E\(tot\)\s*=\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i,
      /\bEtot\b\s*[:=]\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i
    ], toHa);
    gap = firstMatchNum(s, [
      { re: /HOMO[-\s]*LUMO(?:\s+gap)?(?:\s*\(([^)]+)\)|\s*\[([^\]]+)\])?\s*[:=]\s*(\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i, num: 3, unitA: 1, unitB: 2 },
      { re: /\bgap\b(?:\s*\(([^)]+)\)|\s*\[([^\]]+)\])?\s*[:=]\s*(\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i, num: 3, unitA: 1, unitB: 2 }
    ], function (v, unitA, unitB) { return toEv(v, unitA || unitB); });
    var m = s.match(/HOMO(?:\s+Eigenvalue)?\s*[:=]\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?[\s\S]{0,80}?LUMO(?:\s+Eigenvalue)?\s*[:=]\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?/i);
    if (gap == null && m) gap = toEv(parseFloat(m[3]) - parseFloat(m[1]), m[2] || m[4] || "Ha");
    split = firstMatchNum(s, [
      { re: /(?:Rabi|polariton)?\s*split(?:ting)?(?:\s*\(([^)]+)\)|\s*\[([^\]]+)\])?\s*[:=]\s*(\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i, num: 3, unitA: 1, unitB: 2 },
      /\b2g\b\s*[:=]\s*(\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)\s*([A-Za-z\.\-\^0-9]+)?/i
    ], function (v, unitA, unitB) { return toEv(v, unitA || unitB); });
    if (/converged\s*[:=]\s*false/i.test(s)) conv = false;
    else if (/converged\s*[:=]\s*true/i.test(s)) conv = true;
    else if (/not\s+converged|failed\s+to\s+converge/i.test(s)) conv = false;
    else if (/converged\s+SCF|SCF\s+converged|SCF done|FINAL\s+SINGLE\s+POINT\s+ENERGY|TOTAL\s+SCF\s+ENERGY/i.test(s)) conv = true;
    return { ok: true, source: "text", energyHa: energy, gapEv: gap, splitEv: split, converged: conv };
  }

  function formatParsed(p, t) {
    if (!p || !p.ok) return t("bridge.out.empty");
    var lines = [t("bridge.out.source") + ": " + p.source];
    if (p.energyHa != null) lines.push(t("bridge.out.energy") + ": " + p.energyHa.toFixed(8) + " Ha");
    if (p.converged != null) lines.push(t("bridge.out.conv") + ": " + (p.converged ? t("bridge.out.yes") : t("bridge.out.no")));
    if (p.gapEv != null) lines.push(t("bridge.out.gap") + ": " + p.gapEv.toFixed(4) + " eV");
    if (p.splitEv != null) lines.push(t("bridge.out.split") + ": " + p.splitEv.toFixed(4) + " eV");
    if (lines.length === 1) lines.push(t("bridge.out.nodata"));
    return lines.join("\n");
  }

  function refreshImpl() {
    if (typeof document === "undefined") return;
    bindUi();
    var t = App.i18n.t;
    if (!$("bridgeTemplate") || !$("bridgeMsg")) return;
    $("bridgeTemplate").value = makeTemplate(S.target, currentData());
    $("bridgeNote").textContent = t("bridge.note");
    $("bridgeMsg").textContent = t("bridge.msg.ready");
  }

  // Optional decorative panel: never let it throw into the render pipeline.
  function refresh() {
    try { refreshImpl(); }
    catch (e) { if (typeof console !== "undefined" && console.error) console.error("bridge refresh failed:", e); }
  }

  function renderParsed() {
    var out = $("bridgeParsed");
    var inp = $("bridgeImport");
    if (!out || !inp) return;
    var p = parseResult(inp.value || "");
    out.textContent = formatParsed(p, App.i18n.t);
  }

  function bindUi() {
    if (typeof document === "undefined" || S.bound) return;
    var target = $("bridgeTarget"), gen = $("bridgeGenBtn"), copy = $("bridgeCopyBtn"), parseBtn = $("bridgeParseBtn");
    if (!target || !gen || !copy || !parseBtn) return;
    target.value = S.target;
    target.addEventListener("change", function () { S.target = target.value || "pyscf"; refresh(); });
    gen.addEventListener("click", refresh);
    copy.addEventListener("click", function () {
      var ta = $("bridgeTemplate"), t = App.i18n.t;
      ta.select();
      var ok = false;
      try { ok = document.execCommand("copy"); } catch (e) { ok = false; }
      $("bridgeMsg").textContent = ok ? t("bridge.msg.copied") : t("bridge.msg.copyfail");
    });
    // Some browser/webview environments may swallow one of the handlers.
    // Keep both wiring paths to make parse rendering predictable.
    parseBtn.addEventListener("click", function (e) {
      if (e && e.preventDefault) e.preventDefault();
      renderParsed();
    });
    parseBtn.onclick = renderParsed;
    S.bound = true;
  }

  function init(opts) {
    deps = opts || {};
    bindUi();
    refresh();
  }

  App.crossBridge = { init: init, refresh: refresh, makeTemplate: makeTemplate, parseResult: parseResult };
})(typeof globalThis.App === "object" ? globalThis.App : (globalThis.App = {}));
