// Cross-method bridge: export minimal templates and parse external outputs.
// Goal: quick interoperability with PySCF/QED-TDDFT/CavMD workflows.
(function (App) {
  "use strict";
  var deps = null;
  var S = { target: "pyscf" };
  var $ = function (id) { return document.getElementById(id); };

  function atomsFromResult(result) {
    if (!result || !result.atoms || !result.atoms.length) return [];
    var BOHR = 1 / App.engine.ANGSTROM_TO_BOHR;
    return result.atoms.map(function (a) {
      return { sym: App.SYMBOLS[a.Z] || "X", xyz: [a.xyz[0] * BOHR, a.xyz[1] * BOHR, a.xyz[2] * BOHR] };
    });
  }

  function atomsFromPreset(preset) {
    if (!preset || !preset.xyz || !App.engine || !App.engine.parseXYZ) return [];
    try {
      var atoms = App.engine.parseXYZ(preset.xyz);
      var BOHR = 1 / App.engine.ANGSTROM_TO_BOHR;
      return atoms.map(function (a) { return { sym: App.SYMBOLS[a.Z] || "X", xyz: [a.xyz[0] * BOHR, a.xyz[1] * BOHR, a.xyz[2] * BOHR] }; });
    } catch (e) { return []; }
  }

  function currentData() {
    var result = deps && deps.getResult ? deps.getResult() : null;
    var preset = deps && deps.getPreset ? deps.getPreset() : null;
    var prov = deps && deps.getProvenance ? deps.getProvenance() : null;
    var atoms = atomsFromResult(result);
    if (!atoms.length) atoms = atomsFromPreset(preset);
    if (!atoms.length) atoms = [{ sym: "H", xyz: [0, 0, 0] }, { sym: "H", xyz: [0, 0, 0.7414] }];
    var charge = prov && prov.charge != null ? prov.charge : (preset && preset.charge != null ? preset.charge : 0);
    var mult = prov && prov.multiplicity != null ? prov.multiplicity : (result && result.mult != null ? result.mult : (preset && preset.mult) || 1);
    var basis = (result && result.basisName) || (prov && prov.basis) || "STO-3G";
    var method = (prov && prov.method) || (result && result.scf && result.scf.uhf ? "UHF" : "RHF");
    var name = preset ? (preset.formula || preset.id || "molecule") : "custom molecule";
    return { atoms: atoms, basis: basis, charge: charge, multiplicity: mult, method: method, name: name };
  }

  function atomLines(atoms) {
    return atoms.map(function (a) { return a.sym + " " + a.xyz.map(function (v) { return v.toFixed(6); }).join(" "); }).join("\n");
  }

  function makeTemplate(target, data) {
    data = data || {};
    var atoms = data.atoms || [];
    var basis = (data.basis || "STO-3G").toLowerCase();
    var charge = data.charge || 0;
    var mult = data.multiplicity || 1;
    var spin = Math.max(0, mult - 1);
    var method = (data.method || (mult > 1 ? "UHF" : "RHF")).toUpperCase();
    var xyz = atomLines(atoms.length ? atoms : [{ sym: "H", xyz: [0, 0, 0] }, { sym: "H", xyz: [0, 0, 0.7414] }]);
    if (target === "qedtddft") {
      return [
        "# Generated by quantum-field-molecules Cross-method Bridge.",
        "# Minimal scaffold for a PySCF + QED-TDDFT-like workflow (adapt imports to your setup).",
        "from pyscf import gto, scf",
        "",
        "mol = gto.M(atom='''",
        xyz,
        "''', basis='" + basis + "', charge=" + charge + ", spin=" + spin + ")",
        "mf = scf." + (method === "UHF" ? "UHF" : "RHF") + "(mol).run()",
        "",
        "wc_ev = 8.0",
        "g_ev = 0.2",
        "polarization = (0.0, 0.0, 1.0)",
        "# qed = QEDTDDFT(mf, wc_ev=wc_ev, g_ev=g_ev, pol=polarization)",
        "# print(qed.kernel())",
        "print('SCF_ENERGY_HA =', mf.e_tot)"
      ].join("\n");
    }
    if (target === "cavmd") {
      return JSON.stringify({
        schema: "cavmd-input-v1",
        title: data.name || "molecule",
        units: { xyz: "angstrom", energy: "eV" },
        molecule: { charge: charge, multiplicity: mult, atoms: (atoms.length ? atoms : []).map(function (a) { return { symbol: a.sym, xyz: a.xyz.map(function (v) { return +v.toFixed(6); }) }; }) },
        cavity: { wc_ev: 8.0, g_ev: 0.2, polarization: [0, 0, 1] },
        notes: "Template generated from in-browser model; adapt force-field and integrator settings."
      }, null, 2);
    }
    return [
      "# Generated by quantum-field-molecules Cross-method Bridge.",
      "from pyscf import gto, scf",
      "",
      "mol = gto.M(atom='''",
      xyz,
      "''', basis='" + basis + "', charge=" + charge + ", spin=" + spin + ")",
      "mf = scf." + (method === "UHF" ? "UHF" : "RHF") + "(mol)",
      "E = mf.kernel()",
      "print('SCF_ENERGY_HA =', E)"
    ].join("\n");
  }

  function firstNum(obj, keys) {
    for (var i = 0; i < keys.length; i++) {
      var v = obj[keys[i]];
      if (typeof v === "number" && isFinite(v)) return v;
    }
    return null;
  }

  function parseResult(text) {
    if (!text || !String(text).trim()) return { ok: false, source: "none" };
    var s = String(text).trim(), energy = null, gap = null, split = null, conv = null;
    try {
      var j = JSON.parse(s);
      energy = firstNum(j, ["energy", "E", "total_energy", "scf_energy", "etot"]);
      gap = firstNum(j, ["gap", "homo_lumo_gap", "gap_ev"]);
      split = firstNum(j, ["split", "rabi_split", "splitting_ev"]);
      if (typeof j.converged === "boolean") conv = j.converged;
      return { ok: true, source: "json", energyHa: energy, gapEv: gap, splitEv: split, converged: conv };
    } catch (e) { /* text mode */ }
    var m = s.match(/(?:SCF[_\s-]*ENERGY[_\s-]*HA|total[_\s-]*energy|E\(tot\)|Etot)\s*[:=]\s*(-?\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i);
    if (m) energy = parseFloat(m[1]);
    m = s.match(/(?:HOMO[-\s]*LUMO(?:\s+gap)?|gap)\s*[:=]\s*(\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i);
    if (m) gap = parseFloat(m[1]);
    m = s.match(/(?:Rabi|polariton)?\s*split(?:ting)?\s*[:=]\s*(\d+(?:\.\d+)?(?:[Ee][+-]?\d+)?)/i);
    if (m) split = parseFloat(m[1]);
    if (/not\s+converged|failed\s+to\s+converge/i.test(s)) conv = false;
    else if (/converged|SCF done/i.test(s)) conv = true;
    return { ok: true, source: "text", energyHa: energy, gapEv: gap, splitEv: split, converged: conv };
  }

  function formatParsed(p, t) {
    if (!p || !p.ok) return t("bridge.out.empty");
    var lines = [t("bridge.out.source") + ": " + p.source];
    if (p.energyHa != null) lines.push(t("bridge.out.energy") + ": " + p.energyHa.toFixed(8) + " Ha");
    if (p.converged != null) lines.push(t("bridge.out.conv") + ": " + (p.converged ? t("bridge.out.yes") : t("bridge.out.no")));
    if (p.gapEv != null) lines.push(t("bridge.out.gap") + ": " + p.gapEv.toFixed(4) + " eV");
    if (p.splitEv != null) lines.push(t("bridge.out.split") + ": " + p.splitEv.toFixed(4) + " eV");
    if (lines.length === 1) lines.push(t("bridge.out.nodata"));
    return lines.join("\n");
  }

  function refresh() {
    if (typeof document === "undefined") return;
    var t = App.i18n.t;
    if (!$("bridgeTemplate") || !$("bridgeMsg")) return;
    $("bridgeTemplate").value = makeTemplate(S.target, currentData());
    $("bridgeNote").textContent = t("bridge.note");
    $("bridgeMsg").textContent = t("bridge.msg.ready");
  }

  function init(opts) {
    deps = opts || {};
    if (typeof document === "undefined") return;
    var target = $("bridgeTarget"), gen = $("bridgeGenBtn"), copy = $("bridgeCopyBtn"), parse = $("bridgeParseBtn");
    if (!target || !gen || !copy || !parse) return;
    target.value = S.target;
    target.addEventListener("change", function () { S.target = target.value || "pyscf"; refresh(); });
    gen.addEventListener("click", refresh);
    copy.addEventListener("click", function () {
      var ta = $("bridgeTemplate"), t = App.i18n.t;
      ta.select();
      var ok = false;
      try { ok = document.execCommand("copy"); } catch (e) { ok = false; }
      $("bridgeMsg").textContent = ok ? t("bridge.msg.copied") : t("bridge.msg.copyfail");
    });
    parse.addEventListener("click", function () {
      var p = parseResult($("bridgeImport").value || "");
      $("bridgeParsed").textContent = formatParsed(p, App.i18n.t);
    });
    refresh();
  }

  App.crossBridge = { init: init, refresh: refresh, makeTemplate: makeTemplate, parseResult: parseResult };
})(typeof globalThis.App === "object" ? globalThis.App : (globalThis.App = {}));
